project_id = "ssozotdotbdiruyoncpl"

[functions.compute-expense]
verify_jwt = false

[functions.month-summary]
verify_jwt = false

[functions.simulate-drop-income]
verify_jwt = false

[functions.projection-first-million]
verify_jwt = false